In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
submission_df = pd.read_csv('data/sample_submission.csv')
train = pd.read_csv('data/train.csv')
test = pd.read_csv('data/test.csv')

In [3]:
prophet_data = train.rename(columns={'timestamp': 'ds', 'price(원/kg)': 'y'})
prophet_data = prophet_data[['ID', 'ds', 'y']]
prophet_data['ID'] = prophet_data['ID'].str.replace(r'_\d{8}$', '', regex=True)

In [6]:
prophet_data['ds']

           ID          ds       y
0      TG_A_J  2019-01-01     0.0
1      TG_A_J  2019-01-02     0.0
2      TG_A_J  2019-01-03  1728.0
3      TG_A_J  2019-01-04  1408.0
4      TG_A_J  2019-01-05  1250.0
...       ...         ...     ...
59392  RD_F_J  2023-02-27   468.0
59393  RD_F_J  2023-02-28   531.0
59394  RD_F_J  2023-03-01   574.0
59395  RD_F_J  2023-03-02   523.0
59396  RD_F_J  2023-03-03   529.0

[59397 rows x 3 columns]

In [5]:
from prophet import Prophet
import numpy as np
RANDOM_SEED = 990313
np.random.seed(RANDOM_SEED)
def ph_train(df):
    pred_list = []  
    for code in df['ID'].unique():
        d = df[df['ID'] == code].reset_index().drop(['ID'], axis=1).sort_values('ds')
        model = Prophet(
#             growth = 'choose',
#             seasonality_mode = 'choose',
#             yearly_seasonality = 'choose',
#             weekly_seasonality = 'choose',
#             daily_seasonality = 'choose',
#             holidays = 'choose',
#             changepoint_prior_scale = 'choose'
                       )
        model.fit(d)
        future = pd.DataFrame()
        future['ds'] = pd.date_range(start='2023-03-04', periods=28, freq='D') 
        forecast = model.predict(future)        
        pred_y = forecast['yhat'].values
        pred_code = [str(code)] * len(pred_y)
        for y_val, id_val in zip(pred_y, pred_code):
            pred_list.append({'ID': id_val, 'y': y_val})
    pred = pd.DataFrame(pred_list) 
    return pred
pred = ph_train(prophet_data)
submission_df['answer'] = pred['y']
submission_df.to_csv('prophet.csv',index=False)

14:22:36 - cmdstanpy - INFO - Chain [1] start processing
14:22:36 - cmdstanpy - INFO - Chain [1] done processing
14:22:37 - cmdstanpy - INFO - Chain [1] start processing
14:22:37 - cmdstanpy - INFO - Chain [1] done processing
14:22:37 - cmdstanpy - INFO - Chain [1] start processing
14:22:37 - cmdstanpy - INFO - Chain [1] done processing
14:22:37 - cmdstanpy - INFO - Chain [1] start processing
14:22:38 - cmdstanpy - INFO - Chain [1] done processing
14:22:38 - cmdstanpy - INFO - Chain [1] start processing
14:22:38 - cmdstanpy - INFO - Chain [1] done processing
14:22:38 - cmdstanpy - INFO - Chain [1] start processing
14:22:38 - cmdstanpy - INFO - Chain [1] done processing
14:22:39 - cmdstanpy - INFO - Chain [1] start processing
14:22:39 - cmdstanpy - INFO - Chain [1] done processing
14:22:39 - cmdstanpy - INFO - Chain [1] start processing
14:22:39 - cmdstanpy - INFO - Chain [1] done processing
14:22:39 - cmdstanpy - INFO - Chain [1] start processing
14:22:39 - cmdstanpy - INFO - Chain [1] done processing
14:22:40 - cmdstanpy - INFO - Chain [1] start processing
14:22:40 - cmdstanpy - INFO - Chain [1] done processing
14:22:40 - cmdstanpy - INFO - Chain [1] start processing
14:22:40 - cmdstanpy - INFO - Chain [1] done processing
14:22:40 - cmdstanpy - INFO - Chain [1] start processing
14:22:40 - cmdstanpy - INFO - Chain [1] done processing
14:22:41 - cmdstanpy - INFO - Chain [1] start processing
14:22:41 - cmdstanpy - INFO - Chain [1] done processing
14:22:41 - cmdstanpy - INFO - Chain [1] start processing
14:22:41 - cmdstanpy - INFO - Chain [1] done processing
14:22:41 - cmdstanpy - INFO - Chain [1] start processing
14:22:42 - cmdstanpy - INFO - Chain [1] done processing
14:22:42 - cmdstanpy - INFO - Chain [1] start processing
14:22:42 - cmdstanpy - INFO - Chain [1] done processing
14:22:42 - cmdstanpy - INFO - Chain [1] start processing
14:22:42 - cmdstanpy - INFO - Chain [1] done processing
14:22:43 - cmdstanpy - INFO - Chain [1] start processing
14:22:43 - cmdstanpy - INFO - Chain [1] done processing
14:22:43 - cmdstanpy - INFO - Chain [1] start processing
14:22:43 - cmdstanpy - INFO - Chain [1] done processing
14:22:43 - cmdstanpy - INFO - Chain [1] start processing
14:22:43 - cmdstanpy - INFO - Chain [1] done processing
14:22:44 - cmdstanpy - INFO - Chain [1] start processing
14:22:44 - cmdstanpy - INFO - Chain [1] done processing
14:22:44 - cmdstanpy - INFO - Chain [1] start processing
14:22:44 - cmdstanpy - INFO - Chain [1] done processing
14:22:44 - cmdstanpy - INFO - Chain [1] start processing
14:22:45 - cmdstanpy - INFO - Chain [1] done processing
14:22:45 - cmdstanpy - INFO - Chain [1] start processing
14:22:45 - cmdstanpy - INFO - Chain [1] done processing
14:22:45 - cmdstanpy - INFO - Chain [1] start processing
14:22:45 - cmdstanpy - INFO - Chain [1] done processing
14:22:46 - cmdstanpy - INFO - Chain [1] start processing
14:22:46 - cmdstanpy - INFO - Chain [1] done processing
14:22:46 - cmdstanpy - INFO - Chain [1] start processing
14:22:46 - cmdstanpy - INFO - Chain [1] done processing
14:22:46 - cmdstanpy - INFO - Chain [1] start processing
14:22:47 - cmdstanpy - INFO - Chain [1] done processing
14:22:47 - cmdstanpy - INFO - Chain [1] start processing
14:22:47 - cmdstanpy - INFO - Chain [1] done processing
14:22:47 - cmdstanpy - INFO - Chain [1] start processing
14:22:47 - cmdstanpy - INFO - Chain [1] done processing
14:22:48 - cmdstanpy - INFO - Chain [1] start processing
14:22:48 - cmdstanpy - INFO - Chain [1] done processing
14:22:48 - cmdstanpy - INFO - Chain [1] start processing
14:22:48 - cmdstanpy - INFO - Chain [1] done processing
14:22:48 - cmdstanpy - INFO - Chain [1] start processing
14:22:49 - cmdstanpy - INFO - Chain [1] done processing
14:22:49 - cmdstanpy - INFO - Chain [1] start processing
14:22:49 - cmdstanpy - INFO - Chain [1] done processing
14:22:49 - cmdstanpy - INFO - Chain [1] start processing
14:22:49 - cmdstanpy - INFO - Chain [1] done processing
14:22:50 - cmdstanpy - INFO - Chain [1] start processing
14:22:50 - cmdstanpy - INFO - Chain [1] done processing
14:22:50 - cmdstanpy - INFO - Chain [1] start processing
14:22:50 - cmdstanpy - INFO - Chain [1] done processing
14:22:50 - cmdstanpy - INFO - Chain [1] start processing
14:22:51 - cmdstanpy - INFO - Chain [1] done processing
14:22:51 - cmdstanpy - INFO - Chain [1] start processing
14:22:51 - cmdstanpy - INFO - Chain [1] done processing

In [7]:
pred

          ID            y
0     TG_A_J  3636.656770
1     TG_A_J  1103.059517
2     TG_A_J  4248.751151
3     TG_A_J  4168.892426
4     TG_A_J  4203.433211
...      ...          ...
1087  RD_F_J   409.032660
1088  RD_F_J   416.484325
1089  RD_F_J   406.717557
1090  RD_F_J   399.278648
1091  RD_F_J   393.551170

[1092 rows x 2 columns]